### PR TITLE
1.17 version

### PR DESCRIPTION
**Pull request by OverBrave**
If you brought support for 1.17.1, could you release a custom version so we can use it? Many people are waiting for support for 1.17, but the actual developer is not active

### CODE REVIEW

**Comment by SoRadGaming** [comment]
Could you just compile the plugin and upload it here? Doubt these devs will ever respond.

**Comment by Drc-DEV** [comment]
https://github.com/Drc-DEV/Duels/releases/tag/3.4.2

**Review by OverBrave — COMMENTED** [review]
Or is it coming?

**Comment by SrBedrock** [comment]
> > [Drc-DEV/Duels@`3.4.2` (release)](https://github.com/Drc-DEV/Duels/releases/tag/3.4.2)
> 
> This version is identifying players as if they are dueling when they are not, removing their items as if they were items from the dueling kits.

image

**Comment by Realizedd** [comment]
Thanks for putting in the effort to update this to 1.18! Unfortunately, I cannot merge this request as I found the code lacks backward compatibility for older MC versions. However, I've just published 59a875c which supports 1.8 - 1.18, which should hopefully be a good replacement. :smiley:

**Pull request closed without merging**
